version: '3.9'

services:
  app:
    container_name: auth-service
    build: ./
    command: ./auth-service
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: postgres
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: "auth_service"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5436:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admina.net"
      PGADMIN_DEFAULT_PASSWORD: "postgress"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:5050"
    restart: unless-stopped
    depends_on:
      - db